cabal-version:      2.4
name:               proarrow
version:            0
synopsis:           Category theory with a central role for profunctors
homepage:           https://github.com/sjoerdvisscher/proarrow
bug-reports:        https://github.com/sjoerdvisscher/proarrow/issues
license:            BSD-3-Clause
license-file:       LICENSE
author:             Sjoerd Visscher
maintainer:         sjoerd@w3future.com
category:           Math, Categories
tested-with:        GHC ==9.10.3 || ==9.12.2

extra-doc-files:
    CHANGELOG.md
    README.md
    mkdocs.sh

common extensions
    default-language: GHC2024
    ghc-options:      -Wall
    default-extensions:
        BlockArguments
        DefaultSignatures
        DeriveAnyClass
        DerivingVia
        FunctionalDependencies
        OverloadedLists
        NoImplicitPrelude
        NoStarIsType
        PatternSynonyms
        RecordWildCards
        QuantifiedConstraints
        StrictData
        TypeAbstractions
        TypeData
        TypeFamilies
        UndecidableInstances
        UndecidableSuperClasses
        ViewPatterns

library
    import: extensions
    exposed-modules:
        Proarrow
        Proarrow.Adjunction
        Proarrow.Category
        Proarrow.Category.Bicategory
        Proarrow.Category.Bicategory.Adj
        Proarrow.Category.Bicategory.Bidiscrete
        Proarrow.Category.Bicategory.Co
        Proarrow.Category.Bicategory.Hom
        Proarrow.Category.Bicategory.Kan
        Proarrow.Category.Bicategory.LaxFunctor
        Proarrow.Category.Bicategory.Limit
        -- Proarrow.Category.Bicategory.Mod
        Proarrow.Category.Bicategory.MonoidalAsBi
        Proarrow.Category.Bicategory.Op
        Proarrow.Category.Bicategory.Product
        Proarrow.Category.Bicategory.Prof
        Proarrow.Category.Bicategory.Relative
        Proarrow.Category.Bicategory.Strictified
        Proarrow.Category.Bicategory.Sub
        Proarrow.Category.Bicategory.Terminal
        Proarrow.Category.Bicategory.ThinCategoryAsBi
        Proarrow.Category.Enriched
        Proarrow.Category.Enriched.Dagger
        Proarrow.Category.Enriched.Thin
        Proarrow.Category.Equipment
        Proarrow.Category.Equipment.Limit
        Proarrow.Category.Equipment.Stateful
        Proarrow.Category.Instance.Ap
        Proarrow.Category.Instance.BiAsCategory
        Proarrow.Category.Instance.Bool
        Proarrow.Category.Instance.CatFun
        Proarrow.Category.Instance.CatProf
        Proarrow.Category.Instance.Collage
        Proarrow.Category.Instance.Constraint
        Proarrow.Category.Instance.Coproduct
        Proarrow.Category.Instance.Cospan
        Proarrow.Category.Instance.Cost
        Proarrow.Category.Instance.Discrete
        -- Proarrow.Category.Instance.Display
        Proarrow.Category.Instance.Duploid
        Proarrow.Category.Instance.Fam
        Proarrow.Category.Instance.Fin
        Proarrow.Category.Instance.FinHask
        Proarrow.Category.Instance.FinRel
        Proarrow.Category.Instance.FinSet
        Proarrow.Category.Instance.Free
        Proarrow.Category.Instance.Graph
        Proarrow.Category.Instance.Hask
        Proarrow.Category.Instance.IntConstruction
        Proarrow.Category.Instance.Kleisli
        Proarrow.Category.Instance.Linear
        Proarrow.Category.Instance.Mat
        Proarrow.Category.Instance.Nat
        Proarrow.Category.Instance.PointedHask
        Proarrow.Category.Instance.Product
        Proarrow.Category.Instance.Prof
        Proarrow.Category.Instance.Rel
        Proarrow.Category.Instance.Rep
        Proarrow.Category.Instance.Simplex
        Proarrow.Category.Instance.Span
        Proarrow.Category.Instance.Sub
        Proarrow.Category.Instance.Unit
        Proarrow.Category.Instance.Zero
        Proarrow.Category.Instance.ZX
        Proarrow.Category.Internal
        Proarrow.Category.Monoidal
        Proarrow.Category.Monoidal.Action
        Proarrow.Category.Monoidal.Applicative
        Proarrow.Category.Monoidal.Closed
        Proarrow.Category.Monoidal.Coclosed
        Proarrow.Category.Monoidal.CompactClosed
        Proarrow.Category.Monoidal.CopyDiscard
        Proarrow.Category.Monoidal.Distributive
        Proarrow.Category.Monoidal.Endo
        Proarrow.Category.Monoidal.Hypergraph
        Proarrow.Category.Monoidal.Optic
        Proarrow.Category.Monoidal.Rev
        Proarrow.Category.Monoidal.StarAutonomous
        Proarrow.Category.Monoidal.Strength
        Proarrow.Category.Monoidal.Strictified
        Proarrow.Category.Instance.Opposite
        Proarrow.Category.Promonoidal
        Proarrow.Category.Topos
        Proarrow.Colimit
        Proarrow.Colimit.BinaryCoproduct
        Proarrow.Colimit.Coequalizer
        Proarrow.Colimit.Copower
        Proarrow.Colimit.Initial
        Proarrow.Colimit.NaturalNumbers
        Proarrow.Colimit.Pushout
        Proarrow.Core
        Proarrow.Functor
        Proarrow.Limit
        Proarrow.Limit.BinaryProduct
        Proarrow.Limit.Equalizer
        Proarrow.Limit.Power
        Proarrow.Limit.Pullback
        Proarrow.Limit.Terminal
        Proarrow.Monoid
        Proarrow.Object
        Proarrow.Optic
        Proarrow.Profunctor
        Proarrow.Profunctor.Cofree
        Proarrow.Profunctor.Corepresentable
        Proarrow.Profunctor.Free
        Proarrow.Profunctor.Instance.Arrow
        Proarrow.Profunctor.Instance.Cocone
        Proarrow.Profunctor.Instance.Composition
        Proarrow.Profunctor.Instance.Cone
        Proarrow.Profunctor.Instance.Constant
        Proarrow.Profunctor.Instance.Coproduct
        Proarrow.Profunctor.Instance.Costar
        Proarrow.Profunctor.Instance.Coyoneda
        Proarrow.Profunctor.Instance.Day
        Proarrow.Profunctor.Instance.Direp
        Proarrow.Profunctor.Instance.Exponential
        Proarrow.Profunctor.Instance.Fix
        Proarrow.Profunctor.Instance.Fold
        Proarrow.Profunctor.Instance.HaskValue
        Proarrow.Profunctor.Instance.Identity
        Proarrow.Profunctor.Instance.Initial
        Proarrow.Profunctor.Instance.List
        Proarrow.Profunctor.Instance.PastroTambara
        Proarrow.Profunctor.Instance.Product
        Proarrow.Profunctor.Instance.Ran
        Proarrow.Profunctor.Instance.Rift
        Proarrow.Profunctor.Instance.Star
        Proarrow.Profunctor.Instance.Terminal
        Proarrow.Profunctor.Instance.Wrapped
        Proarrow.Profunctor.Instance.Yoneda
        Proarrow.Profunctor.Representable
        Proarrow.Promonad
        Proarrow.Promonad.Cont
        Proarrow.Promonad.Reader
        Proarrow.Promonad.State
        Proarrow.Promonad.Writer
        Proarrow.Squares
        Proarrow.Squares.Limit
        Proarrow.Squares.Relative
        Proarrow.Tools.CCC
        Proarrow.Tools.Diagrams.Dot
        Proarrow.Universal

    build-depends:
        , base >=4.20 && <5
        , containers >=0.6 && <0.8
        , fin >= 0.3.2 && <1
        , vec >= 0.5.1 && <1
        , universe-base >= 1.1.4 && <1.2
    hs-source-dirs:   src

test-suite test
    import: extensions
    type: exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    other-modules:
        Examples.UntypedLambdaCalculus
        Examples.SimplyTypedLambdaCalculus
        Props
        Props.Bool
        Props.Cospan
        Props.Cost
        Props.Dot
        Props.FinHask
        Props.FinRel
        Props.FinSet
        Props.Free
        Props.Hask
        Props.Kleisli
        Props.PointedHask
        Props.Mat
        Props.Simplex
        Props.Span
        Props.ZX
        Testable
        TestFree
    build-depends: proarrow
    build-depends:
        , base >=4.20 && <5
        , containers >=0.6 && <0.8
        , falsify >=0.3 && <0.4
        , fin >= 0.3.2 && <1
        , vec >= 0.5.1 && <1
        , universe-base >= 1.1.4 && <1.2
        , tasty >=1.4 && <1.6
