cabal-version:      2.4
name:               proarrow-equipment
version:            0
synopsis:           Bicategories and proarrow equipments, built on proarrow
homepage:           https://github.com/sjoerdvisscher/proarrow
bug-reports:        https://github.com/sjoerdvisscher/proarrow/issues
license:            BSD-3-Clause
license-file:       LICENSE
author:             Sjoerd Visscher
maintainer:         sjoerd@w3future.com
category:           Math, Categories
tested-with:        GHC ==9.10.3 || ==9.12.2

extra-doc-files:
    CHANGELOG.md

common extensions
    default-language: GHC2024
    ghc-options:      -Wall
    default-extensions:
        BlockArguments
        DefaultSignatures
        DeriveAnyClass
        DerivingVia
        FunctionalDependencies
        OverloadedLists
        NoImplicitPrelude
        NoStarIsType
        PatternSynonyms
        RecordWildCards
        QuantifiedConstraints
        StrictData
        TypeAbstractions
        TypeData
        TypeFamilies
        UndecidableInstances
        UndecidableSuperClasses
        ViewPatterns

library
    import: extensions
    exposed-modules:
        Proarrow.Bicategory
        Proarrow.Bicategory.Adj
        Proarrow.Bicategory.Bidiscrete
        Proarrow.Bicategory.Co
        Proarrow.Bicategory.Hom
        Proarrow.Bicategory.Kan
        Proarrow.Bicategory.LaxFunctor
        Proarrow.Bicategory.Limit
        -- Proarrow.Bicategory.Mod
        Proarrow.Bicategory.MonoidalAsBi
        Proarrow.Bicategory.Op
        Proarrow.Bicategory.Product
        Proarrow.Bicategory.Prof
        Proarrow.Bicategory.Relative
        Proarrow.Bicategory.Strictified
        Proarrow.Bicategory.Sub
        Proarrow.Bicategory.Terminal
        Proarrow.Bicategory.ThinCategoryAsBi
        Proarrow.Equipment
        Proarrow.Equipment.Limit
        Proarrow.Equipment.Stateful
        Proarrow.Category.Instance.BiAsCategory
        Proarrow.Category.Instance.CatFun
        Proarrow.Category.Instance.CatProf
        -- Proarrow.Category.Instance.Display
        Proarrow.Category.Monoidal.Endo
        Proarrow.Equipment.Squares
        Proarrow.Equipment.Squares.Limit
        Proarrow.Equipment.Squares.Relative

    build-depends:
        , base >=4.20 && <5
        , fin >= 0.3.2 && <1
        , proarrow
    hs-source-dirs:   src
